### ISSUE TITLE
package don t work with new version of gatsby 4

### ISSUE THREAD

**Issue by aimadgh** [guyromellemagayano/gatsby-source-bigcommerce#53]
warn Plugin @epicdesignlabs/gatsby-source-bigcommerce is not compatible with
your gatsby version 4.0.2 - It requires gatsby@^3.10.1
warn Plugin @epicdesignlabs/gatsby-source-bigcommerce is not compatible with
your gatsby version 4.0.2 - It requires gatsby@^3.10.1

**Comment by guyromellemagayano** [comment]
@aimadgh Hey there. I will look into this issue and will release an updated version in few hours. Thanks for report.

**Comment by aimadgh** [comment]
that gonna be helpful, thanks for you time
