### ISSUE TITLE
NPM install is suddently not working.

### ISSUE THREAD

**Issue by andrew-knott** [guyromellemagayano/gatsby-source-bigcommerce#65]
npm install @epicdesignlabs/gatsby-source-bigcommerce

and equivalent yarn is no longer working (404). It's broken our CI.

**Comment by guyromellemagayano** [comment]
Im sorry to hear that @andrew-knott. There has been some changes to the ownership of the custom plugin. I will still be the principal owner of this custom repo but it will no longer be part of the `epicdesignlabs` organization. I will release a newer version of the plugin under `@guyromellemagayano/gatsby-source-bigcommerce` in few hours which will support Gatsby 4.0. Im currently finalizing the plugin. Will let you know if its already live.

Cheers 🥂

**Comment by pinktonio** [comment]
@guyromellemagayano  can you publish the repo to npm with the current tags to get our CI pipeline back to work with our Gatsby 3 implementation?

**Comment by guyromellemagayano** [comment]
@pinktonio Sure. I will add support for Gatsby `v3` as well. I'm currently testing and adding fixes to the current plugin before I will release it. Will update you in the next few hours at the earliest.

**Comment by guyromellemagayano** [comment]
@pinktonio @andrew-knott The plugin is now already live, https://www.npmjs.com/package/@guyromellemagayano/gatsby-source-bigcommerce. Feel free to test them out. I will close this ticket already. 

Post another ticket for any issues. Thanks

Cheers 🥂
